### ISSUE TITLE
Slide panel does nothing

### ISSUE THREAD

**Issue by elliottwilliams** [matchboxcowork/matchboxstudio.org#6]
I noticed that the panel that appears when a user clicks the "+" button doesn't do anything:

![slide-panel](https://cloud.githubusercontent.com/assets/910198/16344852/d9ed35f2-3a0c-11e6-9e14-2090e6a94623.gif)

In the code, it looks like this is supposed to be a twitter feed...@mikelberger do you remember what this was used for? If it's no longer needed, I can just remove the button and the panel entirely.

**Comment by mikelberger** [comment]
It should be 3 quotes up there. A long time ago it pulled in the last 3
tweets, but we changed it to static quotes. I'm not sure how/when that
broke.

On the matchboxstudio.org/entrepreneur page, you can see an example of how
this works.

[image: Inline image 1]

**Comment by elliottwilliams** [comment]
Gotcha. Should the quotes be the same as what's on /entrepreneur?

Glad we have version control now! :)

**Comment by mikelberger** [comment]
Sorry for the delay. Wanted to hunt down what it used to be. Thanks Wayback
Machine.

[image: Inline image 1]

MatchBOX
The group generated by work is greater than the sum of elements in the
group. -Tennenhouse

Coworking
I have not failed, I have just found 10,000 ways that will not work. -Edison

Studio
Rather than no, because...yes, if. -Buzz
